/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BabyNFT__factory } from "./BabyNFT__factory";
export { NFTDummy__factory } from "./NFTDummy__factory";
